### ISSUE TITLE
Think about dropping babel as dev dependency

### ISSUE THREAD

**Issue by fhemberger** [bencooling/memshaw#3]
If you decide on having hapi v10.0.0 as minimum version for memshaw, you don't need babel any more for ES6 compilation, as it requires Node.js v4, which supports arrow functions. The only change required would be the use of regular `require()` calls instead of using `import`.

**Comment by bencooling** [comment]
I agree; thanks for bringing that to my attention. Ill try and have something up tonight.

**Comment by bencooling** [comment]
Done. See [v0.1.6](https://github.com/bencooling/memshaw/releases/tag/v0.1.6).

**Comment by fhemberger** [comment]
Cool, thanks!
